# -*- mode: ruby -*-
# vi: set ft=ruby :

$sysprep = <<'SYSPREP'
& $env:windir\system32\sysprep\sysprep.exe /generalize /oobe /unattend:C:\logs\unattend.xml /quiet /shutdown
SYSPREP

$choco = <<'CHOCO'
Set-ExecutionPolicy -Bypass -Force
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
#Write-Host "Setting the path to c:\programdata\chocolatey"
#$path = [system.Environment]::GetEnvironmentVariable("path")
#$pad = $path + ";c:\programdata\chocolatey"
#[System.Environment]::SetEnvironmentVariable("path","$pad") 
#Write-Host "Setting the chocolateypath to c:\programdata\chocolatey"
#$path = [system.Environment]::GetEnvironmentVariable("path")
#[System.Environment]::SetEnvironmentVariable("chocolateypath","c:\programdata\chocolatey") 
invoke-restmethod -uri https://gist.githubusercontent.com/jacqinthebox/5a8e6025b1eb37d65f1e02fc9e75cc06/raw/d38e25533eddb330adff35e9d6b62b4568eeb04b/install-vs.ps1 -Outfile c:\users\vagrant\desktop\install.ps1

choco install VisualStudio2015Community --yes --force --packageParameters "--AdminFile "
CHOCO

Vagrant.configure(2) do |config|
  config.vm.define "w10" 
  config.vm.box = "jacqinthebox/windows10LTSB"
  config.vm.hostname = "w10" 
  config.vm.network "private_network", ip: "192.168.56.60"
  config.vm.network :forwarded_port, guest: 3389, host: 33960, id: "rdp", auto_correct: true

   config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
  end
  
  #config.vm.provision :shell, inline: $sysprep

end
