# -*- mode: ruby -*-
# vi: set ft=ruby :

$devenv = <<'DEVENV'
$script = ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/jacqinthebox/packer-templates/master/extras/devmachine/install-extra.ps1')) | Invoke-Expression 
DEVENV

Vagrant.configure("2") do |config|
  config.vm.define "lab01" do |lab01_config|
    lab01_config.vm.box = "windows10"
    #lab01_config.vm.box = "jacqinthebox/windowsserver2016"
  
    lab01_config.vm.network "forwarded_port", guest: 3389, host: 13389, auto_correct: true
    lab01_config.vm.network "forwarded_port", guest: 5985, host: 15985, id: "winrm", auto_correct:true
    #config.vm.network "private_network", ip: "192.168.56.60"

    lab01_config.vm.provider "parallels" do |p|
      p.name = "lab01"
      p.memory = "4096"
      p.cpus = 2
      p.linked_clone = true	
      p.update_guest_tools = true	
    end
    lab01_config.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.linked_clone = true
      v.customize ["modifyvm", :id, "--vram", "128"]
      v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
  end

  config.vm.define "lab02" do |lab02_config|
    lab02_config.vm.box = "windows10"
    #lab02_config.vm.box = "jacqinthebox/windowsserver2016"
    lab02_config.vm.provider "parallels" do |p|
      p.name = "lab02"
      p.memory = "4096"
      p.cpus = 2
      p.linked_clone = true	
      p.update_guest_tools = true	
    end
  
    lab02_config.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.linked_clone = true
      v.customize ["modifyvm", :id, "--vram", "128"]
      v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
  end
  config.vm.provision :shell, :inline => $devenv
end
